language: java
sudo: true
jdk:
  - oraclejdk7
  - openjdk7
branches:
  only:
    - master
    - development
    - travis
    
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y build-essential curl git m4 ruby texinfo libbz2-dev libcurl4-openssl-dev libexpat-dev libncurses-dev zlib1g-dev
  - git clone https://github.com/Homebrew/linuxbrew.git ~/.linuxbrew
  - export PATH="$HOME/.linuxbrew/bin:$PATH"
  - export MANPATH="$HOME/.linuxbrew/share/man:$MANPATH"
  - export INFOPATH="$HOME/.linuxbrew/share/info:$INFOPATH"
  - brew install mruby
  - cd src/resources
  - xxd -i java_class.rb java_class.h
  - gcc -I$(JAVA_HOME)/include -I$(JAVA_HOME)/include/linux -Wl,--whole-archive -lmruby -Wl,--no-whole-archive -fPIC -shared -o libmrubystate.so MRubyState.c
  - cd ../..

install: mvn install -DskipTests=true
script: mvn test
